### ISSUE TITLE
RepEx 2d doesn't work (see below) 

### ISSUE THREAD

**Issue by taisung** [radical-cybertools/radical.repex.at#12]
(myenv)[taisung@taisung-fedora amber_pattern_b_2d]$ sh launcher_amber_2d.sh 
/usr/people/taisung/myenv/lib/python2.7/site-packages/pkg_resources.py:1045: UserWarning: /usr/people/taisung/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
2014:12:05 09:45:02 radical.pilot.MainProcess: [INFO    ] radical.pilot version: 0.21 (v0.21)

---
-    RepEx simulation: AMBER + Salt Concentration + RE pattern B    *
  *********************************************************************
  Using default Amber path for trestles.sdsc.xsede.org
  Using default Mongo DB url
  Traceback (most recent call last):
  File "launch_simulation_pattern_b_amber_2d.py", line 54, in <module>
    pilot_manager, pilot_object, session = pilot_kernel.launch_pilot()
  File "/usr/people/taisung/myenv/lib/python2.7/site-packages/RepEx-0.1-py2.7.egg/pilot_kernels/pilot_kernel.py", line 73, in launch_pilot
    session = radical.pilot.Session(database_url=self.dburl, database_name='repex-tests')
  File "/usr/people/taisung/myenv/lib/python2.7/site-packages/radical/pilot/session.py", line 123, in **init**
    self._debug_helper = ru.DebugHelper ()
  AttributeError: 'module' object has no attribute 'DebugHelper'

**Comment by antonst** [comment]
Taisung, was this issue resolved for you with the latest radical utils installation? If so, can I close this issue then?

If not I guess that you need to do is
1. install radical utils in a fresh virtualenv: pip install radical.utils
2. install RepEx

Thanks,
Antons
