### ISSUE TITLE
input json file not parsed correctly?

### ISSUE THREAD

**Issue by haoyuanchen** [radical-cybertools/radical.repex.at#13]
When I run the 2d example, all the replicas have a temperature of 323.0 instead of different temperatures. I tried to remove the line "init_temperature": "323.0" but it's still the same, which means the "min_temperature" and "max_temperature" are not passed into the program. The salt concentration dimension seems fine though. 

Also, the "number_of_cycles": "3" seems not working either. It will run for 12 cycles instead of 3...

**Comment by haoyuanchen** [comment]
I've fixed the temperature issue, but I'm unable to find out why the number of cycles are incorrect...

**Comment by antonst** [comment]
Hi Haoyuan, it was incorrectly specified print messages, should be fixed now.

Thanks,
Antons
