### ISSUE TITLE
defining exchange groups in 2D

### ISSUE THREAD

**Issue by haoyuanchen** [radical-cybertools/radical.repex.at#17]
Hi Antons,

As we've discussed this morning, if we're running a 2D replica exchange simulation, for each exchange stage it should only exchange within one dimension and all the exchange partners should have the same value of the non-exchange variable. For example, if we have 4 replicas: 
#0 (T1, S1)
#1 (T1, S2)
#2 (T2, S1)
#3 (T2, S2)

in a temperature exchange stage it should try to exchange (#0 with #2), and (#1 with #3) (no inter-group exchanges!). In a salt concentration exchange stage, it should try to exchange (#0 with #1), and (#2 with #3) (no inter-group exchanges!). If two replicas are different in both T and S (say, #0 and #3), then we shouldn't try to exchange them at all.

Thanks!
Haoyuan

**Comment by antonst** [comment]
Hi Haoyuan,

Will be implemented.

Thanks,
Antons
