### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'uid'

### ISSUE THREAD

**Issue by jhonsen** [radical-cybertools/radical.repex.at#21]
I was trying to run name_scheme on local system, but I kept getting this error.
Any advises?

  File "launch_simulation_scheme_3_namd.py", line 63, in <module>
    pilot_kernel.run_simulation( replicas, pilot_object, session, md_kernel )
  File "/Users/Jhonsen/myenv/lib/python2.7/site-packages/RepEx-0.1-py2.7.egg/pilot_kernels/pilot_kernel_scheme_3.py", line 71, in run_simulation
    unit_manager.add_pilots(pilot_object)
  File "/Users/Jhonsen/myenv/lib/python2.7/site-packages/radical.pilot-0.25-py2.7.egg/radical/pilot/unit_manager.py", line 272, in add_pilots
    if  pilot.uid in pilot_ids :
AttributeError: 'NoneType' object has no attribute 'uid'

**Comment by antonst** [comment]
Can you please specify which branch you are using?

**Comment by jhonsen** [comment]
My apology for the delayed response.
I found that I mixed up devel and master branches and wasn't able to run on both local system and Stampede. I recently installed master release (https://github.com/radical-cybertools/RepEx/issues/18) and also downgraded to previous versions (https://github.com/radical-cybertools/RepEx/issues/23).  
Now, as of yesterday (4/27), I was able to start up a run (name scheme1) on Stampede but I haven't really seen it completed the whole cycle as specified in the example config and json files. I will be testing it again tomorrow (as Stampede is closed today for maintenance.)

In the meantime, I'm still having trouble running on local system with the error below (in addition to the "AttributeError" I first described). 
Error: Resource key 'localhost:local' is not known. 
I'm pretty sure I chose the correct value for the "resource" line, though I guess I assumed using the localhost.macos.x86.64 option would be ok for a dual quad core intel (on Mac 2009Pro).

**Comment by antonst** [comment]
Please try to use feature/2d-prof branch. It will soon be merged with master. Currently master is several releases behind the underlying software stack so there might be some issues. Please let me know what was your experience with feature/2d-prof.

**Comment by jhonsen** [comment]
Nice... the feature/2d-prof branch works!

Although, I did find another error message that I was able to resolve by editing CYCLE to CYCLES in the following:

Traceback (most recent call last):
  File "launch_simulation_scheme_2_namd.py", line 55, in <module>
    pilot_kernel.run_simulation( replicas, pilot_object, session, md_kernel )
  File "/Users/Jhonsen/myenv/lib/python2.7/site-packages/RepEx-0.1-py2.7.egg/pilot_kernels/pilot_kernel_scheme_2.py", line 146, in run_simulation
    for current_cycle in range(1,CYCLE):
NameError: global name 'CYCLE' is not defined

Thanks

**Comment by antonst** [comment]
Problem on master was with not working mongo-db url (scheme-1). It is fixed now. So if you want to try out some other schemes on master feel  free to do so and let us know if something is not working.

Thanks,
Antons
