### ISSUE TITLE
umbrella sampling swap matrix all zero (2d-prof branch)

### ISSUE THREAD

**Issue by haoyuanchen** [radical-cybertools/radical.repex.at#22]
The simulation finished normally but the swap matrices are all zero. In the exchange step it seems that all the computing units only read in one RST file. For example, when I do "ls -l " inside a folder of a matrix-calculation computing unit in a 4-replica simulation, I get

unit-5535620a460ff73653d9e85d:
total 36
-rw------- 1 chen1990 G-803297 8060 Apr 20 15:31 ala10_remd_0_1.rst
-rw------- 1 chen1990 G-803297  315 Apr 20 15:31 ala10_us.mdin
-rw------- 1 chen1990 G-803297   83 Apr 20 15:31 ala10_us.RST.0
-rw------- 1 chen1990 G-803297 9801 Apr 20 15:31 amber_matrix_calculator_pattern_b.py
-rwx------ 1 chen1990 G-803297  597 Apr 20 15:31 radical_pilot_cu_launch_script-1XVZPY.sh
-rw------- 1 chen1990 G-803297    0 Apr 20 15:31 STDERR
-rw------- 1 chen1990 G-803297  103 Apr 20 15:31 STDOUT

All numbers in STDOUT are zero.

Below is the radical_pilot_cu_launch_script-1XVZPY.sh file, we can see that "all_restraints" list is not correct
# !/bin/bash -l

cd /work/02938/chen1990/radical.pilot.sandbox/pilot-55356101460ff73653d9e84f/unit-5535620a460ff73653d9e85d
module load TACC
module load amber/12.0

python "amber_matrix_calculator_pattern_b.py" "{\"all_restraints\": [\"ala10_us.RST.3\", \"ala10_us.RST.3\", \"ala10_us.RST.3\", \"ala10_us.RST.3\"], \"replica_cycle\": \"1\", \"base_name\": \"ala10_remd\", \"replicas\": \"4\", \"amber_input\": \"ala10_us.mdin\", \"amber_path\": \"/opt/apps/intel13/mvapich2_1_9/amber/12.0/bin/sander.MPI\", \"amber_parameters\": \"ala10.prmtop\", \"init_temp\": \"300.0\", \"replica_id\": \"3\"}"

Thanks!

**Comment by antonst** [comment]
I have addressed issue with RST files but now it results in:

Traceback (most recent call last):
  File "amber_matrix_calculator_pattern_b.py", line 233, in <module>
    r.set_rstr(rstr_entry); r.calc_energy()
  File "amber_matrix_calculator_pattern_b.py", line 92, in set_rstr
    if int(atom) % 2: self.rstr_atoms_crds.append(self.crd_data[int(atom)/2+2][:36].split())
IndexError: list index out of range

can you please explain what is going on here? can you please fix this issue?

**Comment by haoyuanchen** [comment]
This is fixed now in the latest commit. Thanks!
