### ISSUE TITLE
3d replica issue

### ISSUE THREAD

**Issue by haoyuanchen** [radical-cybertools/radical.repex.at#26]
Hi Antons,

It seems that the replicas are not initiated correctly. Below is from a 3d (T,S,U) run with 2x2x2 replicas. We can see that replica 0 and 1, 2 and 3, 4 and 5, 6 and 7 have exactly the same parameters.

0
  temp0 = **300**, ig = -1,
  saltcon = **0.0**,
 &rst iat=49,55,57,59 r1=0.0 **r2=200.0 r3=200.0** r4=300.0 rk2=100 rk3=100 /
1
  temp0 = **300**, ig = -1,
  saltcon = **0.0**,
 &rst iat=49,55,57,59 r1=0.0 **r2=200.0 r3=200.0** r4=300.0 rk2=100 rk3=100 /
2
  temp0 = **300**, ig = -1,
  saltcon = **1.0**,
 &rst iat=49,55,57,59 r1=0.0 **r2=200.0 r3=200.0** r4=300.0 rk2=100 rk3=100 /
3
  temp0 = **300**, ig = -1,
  saltcon = **1.0**,
 &rst iat=49,55,57,59 r1=0.0 **r2=200.0 r3=200.0** r4=300.0 rk2=100 rk3=100 /
4
  temp0 = **600**, ig = -1,
  saltcon = **0.0**,
 &rst iat=49,55,57,59 r1=0.0 **r2=220.0 r3=220.0** r4=300.0 rk2=100 rk3=100 /
5
  temp0 = **600**, ig = -1,
  saltcon = **0.0**,
 &rst iat=49,55,57,59 r1=0.0 **r2=220.0 r3=220.0** r4=300.0 rk2=100 rk3=100 /
6
  temp0 = **600**, ig = -1,
  saltcon = **1.0**,
 &rst iat=49,55,57,59 r1=0.0 **r2=220.0 r3=220.0** r4=300.0 rk2=100 rk3=100 /
7
  temp0 = **600**, ig = -1,
  saltcon = **1.0**,
 &rst iat=49,55,57,59 r1=0.0 **r2=220.0 r3=220.0** r4=300.0 rk2=100 rk3=100 /

What we probably should have is:

0
  temp0 = **300**, ig = -1,
  saltcon = **0.0**,
 &rst iat=49,55,57,59 r1=0.0 **r2=200.0 r3=200.0** r4=300.0 rk2=100 rk3=100 /
1
  temp0 = **300**, ig = -1,
  saltcon = **0.0**,
 &rst iat=49,55,57,59 r1=0.0 **r2=220.0 r3=220.0** r4=300.0 rk2=100 rk3=100 /
2
  temp0 = **300**, ig = -1,
  saltcon = **1.0**,
 &rst iat=49,55,57,59 r1=0.0 **r2=200.0 r3=200.0** r4=300.0 rk2=100 rk3=100 /
3
  temp0 = **300**, ig = -1,
  saltcon = **1.0**,
 &rst iat=49,55,57,59 r1=0.0 **r2=220.0 r3=220.0** r4=300.0 rk2=100 rk3=100 /
4
  temp0 = **600**, ig = -1,
  saltcon = **0.0**,
 &rst iat=49,55,57,59 r1=0.0 **r2=200.0 r3=200.0** r4=300.0 rk2=100 rk3=100 /
5
  temp0 = **600**, ig = -1,
  saltcon = **0.0**,
 &rst iat=49,55,57,59 r1=0.0 **r2=220.0 r3=220.0** r4=300.0 rk2=100 rk3=100 /
6
  temp0 = **600**, ig = -1,
  saltcon = **1.0**,
 &rst iat=49,55,57,59 r1=0.0 **r2=200.0 r3=200.0** r4=300.0 rk2=100 rk3=100 /
7
  temp0 = **600**, ig = -1,
  saltcon = **1.0**,
 &rst iat=49,55,57,59 r1=0.0 **r2=220.0 r3=220.0** r4=300.0 rk2=100 rk3=100 /

Thanks!

**Comment by haoyuanchen** [comment]
Also, in the (T,U,U) run, the replicas are not assigned with correct parameters. Below is from a 2x2x2 run with the default parameters:

dihedral
 &rst iat=49,55,57,59 r1=0.0 r2=140.0 r3=140.0 r4=300.0 rk2=100 rk3=100 /
 &rst iat=55,57,59,61 r1=0.0 r2=200.0 r3=200.0 r4=300.0 rk2=100 rk3=100 /
dihedral
 &rst iat=49,55,57,59 r1=0.0 r2=140.0 r3=140.0 r4=300.0 rk2=100 rk3=100 /
 &rst iat=55,57,59,61 r1=0.0 r2=200.0 r3=200.0 r4=300.0 rk2=100 rk3=100 /
dihedral
 &rst iat=49,55,57,59 r1=0.0 r2=140.0 r3=140.0 r4=300.0 rk2=100 rk3=100 /
 &rst iat=55,57,59,61 r1=0.0 r2=200.0 r3=200.0 r4=300.0 rk2=100 rk3=100 /
dihedral
 &rst iat=49,55,57,59 r1=0.0 r2=140.0 r3=140.0 r4=300.0 rk2=100 rk3=100 /
 &rst iat=55,57,59,61 r1=0.0 r2=200.0 r3=200.0 r4=300.0 rk2=100 rk3=100 /
dihedral
 &rst iat=49,55,57,59 r1=0.0 r2=160.0 r3=160.0 r4=300.0 rk2=100 rk3=100 /
 &rst iat=55,57,59,61 r1=0.0 r2=220.0 r3=220.0 r4=300.0 rk2=100 rk3=100 /
dihedral
 &rst iat=49,55,57,59 r1=0.0 r2=160.0 r3=160.0 r4=300.0 rk2=100 rk3=100 /
 &rst iat=55,57,59,61 r1=0.0 r2=220.0 r3=220.0 r4=300.0 rk2=100 rk3=100 /
dihedral
 &rst iat=49,55,57,59 r1=0.0 r2=160.0 r3=160.0 r4=300.0 rk2=100 rk3=100 /
 &rst iat=55,57,59,61 r1=0.0 r2=220.0 r3=220.0 r4=300.0 rk2=100 rk3=100 /
dihedral
 &rst iat=49,55,57,59 r1=0.0 r2=160.0 r3=160.0 r4=300.0 rk2=100 rk3=100 /
 &rst iat=55,57,59,61 r1=0.0 r2=220.0 r3=220.0 r4=300.0 rk2=100 rk3=100 /

The first 4 replicas have exactly the same parameters, so do the other 4.

Thanks!

**Comment by antonst** [comment]
Thanks! There was index mistake. Can you please verify that latest commit addresses this issue?

**Comment by haoyuanchen** [comment]
Yes, the latest commit solved this issue. Thanks!
