### ISSUE TITLE
TUU example not working (6-1-2015 morning check-out)

### ISSUE THREAD

**Issue by taisung** [radical-cybertools/radical.repex.at#29]
---

radical.utils: \* master 
saga-python: \* master 
radical.pilot: \* devel 
RepEx: \* feature/2d-prof 

---

timestamp zero: 1433160374.88
2015:06:01 08:06:15 5158   MainThread   radical.pilot         : [INFO    ] radical.pilot        version: 0.33
Using default Amber path for stampede.tacc.utexas.edu
rid: 0 temp: 300.000000 us1: 151.000000 us2: 161.000000 
rid: 1 temp: 300.000000 us1: 151.000000 us2: 162.000000 
rid: 2 temp: 600.000000 us1: 151.000000 us2: 161.000000 
rid: 3 temp: 600.000000 us1: 151.000000 us2: 162.000000 
rid: 4 temp: 300.000000 us1: 152.000000 us2: 161.000000 
rid: 5 temp: 300.000000 us1: 152.000000 us2: 162.000000 
rid: 6 temp: 600.000000 us1: 152.000000 us2: 161.000000 
rid: 7 temp: 600.000000 us1: 152.000000 us2: 162.000000 
2015:06:01 08:06:15 5158   MainThread   radical.pilot         : [INFO    ] using database url  mongodb://ec2-54-221-194-147.compute-1.amazonaws.com:24242/
2015:06:01 08:06:15 5158   MainThread   radical.pilot         : [INFO    ] using database name repex-tests
2015:06:01 08:06:15 5158   MainThread   radical.pilot         : [INFO    ] Loaded resource configurations for das4.fs2
2015:06:01 08:06:15 5158   MainThread   radical.pilot         : [INFO    ] Loaded resource configurations for ncar.yellowstone
2015:06:01 08:06:15 5158   MainThread   radical.pilot         : [INFO    ] Loaded resource configurations for radical.tutorial
2015:06:01 08:06:15 5158   MainThread   radical.pilot         : [INFO    ] Loaded resource configurations for stfc.joule
2015:06:01 08:06:15 5158   MainThread   radical.pilot         : [INFO    ] Loaded resource configurations for rice.biou
2015:06:01 08:06:15 5158   MainThread   radical.pilot         : [INFO    ] Loaded resource configurations for rice.davinci
2015:06:01 08:06:15 5158   MainThread   radical.pilot         : [INFO    ] Loaded resource configurations for lrz.supermuc
2015:06:01 08:06:15 5158   MainThread   radical.pilot         : [INFO    ] Loaded resource configurations for iu.bigred2
2015:06:01 08:06:15 5158   MainThread   radical.pilot         : [INFO    ] Loaded resource configurations for iu.bigred2_ccm
2015:06:01 08:06:15 5158   MainThread   radical.pilot         : [INFO    ] Loaded resource configurations for local.localhost
2015:06:01 08:06:15 5158   MainThread   radical.pilot         : [INFO    ] Loaded resource configurations for ncsa.bw_ccm
2015:06:01 08:06:15 5158   MainThread   radical.pilot         : [INFO    ] Loaded resource configurations for ncsa.bw
2015:06:01 08:06:15 5158   MainThread   radical.pilot         : [INFO    ] Loaded resource configurations for xsede.stampede
2015:06:01 08:06:15 5158   MainThread   radical.pilot         : [INFO    ] Loaded resource configurations for xsede.trestles
2015:06:01 08:06:15 5158   MainThread   radical.pilot         : [INFO    ] Loaded resource configurations for xsede.gordon
2015:06:01 08:06:15 5158   MainThread   radical.pilot         : [INFO    ] Loaded resource configurations for xsede.blacklight
2015:06:01 08:06:15 5158   MainThread   radical.pilot         : [INFO    ] Loaded resource configurations for xsede.lonestar
2015:06:01 08:06:15 5158   MainThread   radical.pilot         : [INFO    ] Loaded resource configurations for nersc.hopper_ccm
2015:06:01 08:06:15 5158   MainThread   radical.pilot         : [INFO    ] Loaded resource configurations for nersc.hopper
2015:06:01 08:06:15 5158   MainThread   radical.pilot         : [INFO    ] Loaded resource configurations for nersc.edison
2015:06:01 08:06:15 5158   MainThread   radical.pilot         : [INFO    ] Loaded resource configurations for nersc.edison_ccm
2015:06:01 08:06:15 5158   MainThread   radical.pilot         : [INFO    ] Loaded resource configurations for epsrc.archer
2015:06:01 08:06:15 5158   MainThread   radical.pilot         : [INFO    ] Loaded resource configurations for futuregrid.xray
2015:06:01 08:06:15 5158   MainThread   radical.pilot         : [INFO    ] Loaded resource configurations for futuregrid.echo
2015:06:01 08:06:15 5158   MainThread   radical.pilot         : [INFO    ] Loaded resource configurations for futuregrid.india
2015:06:01 08:06:15 5158   MainThread   radical.pilot         : [INFO    ] Loaded resource configurations for futuregrid.bravo
2015:06:01 08:06:15 5158   MainThread   radical.pilot         : [INFO    ] Loaded resource configurations for futuregrid.xray_ccm
2015:06:01 08:06:15 5158   MainThread   radical.pilot         : [INFO    ] Loaded resource configurations for futuregrid.delta
2015:06:01 08:06:15 5158   MainThread   radical.pilot         : [ERROR   ] session create failed
Traceback (most recent call last):
  File "/usr/people/taisung/myenv/lib/python2.7/site-packages/radical/pilot/session.py", line 225, in **init**
    db_name = database_name)
  File "/usr/people/taisung/myenv/lib/python2.7/site-packages/radical/pilot/db/database.py", line 105, in new
    dbs.create(sid, name, creation_time)
  File "/usr/people/taisung/myenv/lib/python2.7/site-packages/radical/pilot/db/database.py", line 138, in create
    raise DBEntryExistsException ("Session '%s' already exists." % sid)
DBEntryExistsException: Session 'rp.session.taisung-fedora.taisung.016587.0001' already exists.
2015:06:01 08:06:15 5158   MainThread   radical.pilot         : [DEBUG   ] session rp.session.taisung-fedora.taisung.016587.0001 closing
Exception AttributeError: "'Session' object has no attribute '_dbs'" in <bound method Session.__del__ of <radical.pilot.session.Session object at 0x7efefb5ec2d0>> ignored
Traceback (most recent call last):
  File "launch_simulation_pattern_b_3d_tuu.py", line 73, in <module>
    session.close (cleanup=False)
NameError: name 'session' is not defined

**Comment by andre-merzky** [comment]
Hi Taisung, 

Sorry for this one.  It seems we create the session ID incorrectly when some tmp files got deleted, eg. after reboot.  Would you mind doing the following:

```
echo 1000 > /tmp/rp_taisung_016587.cnt
```

and run again?  We'll  fix that problem in the next RP release.

Thanks, Andre.

**Comment by antonst** [comment]
since RP ticket is closed, I am closing this one as well.
