### ISSUE TITLE
T dimension issue in TUU

### ISSUE THREAD

**Issue by haoyuanchen** [radical-cybertools/radical.repex.at#36]
As a follow-up of the issue I brought up in today's meeting (7/27), there're exchanges happening in T dimension if replicas differ in temperature by only 1 K. However, when I increase the gap to 5 K, no exchanges in T dimension happened, which is against the physical intuition.

Then I found that the energy differences (from the matrix column files) for T dimension is orders of magnitude larger than for U dimension, which resulted in the fact that virtually no exchanges in T dimension could be accepted.

There could be something wrong in the temperature exchange codes. I'll continue to investigate this.

**Comment by haoyuanchen** [comment]
Just an update, the T dimension exchange seems to work normally when I run the ace_ala_nme example. The previous issue was observed when running the phos_trans example. So it might depends on the real physical system. I'll continue to investigate this and, if you observed different exchange behaviors, please let me know.

**Comment by antonst** [comment]
Thanks for the update! I will look into this as well.

**Comment by haoyuanchen** [comment]
With the current code, the temperature exchange seems to be fine.
