### ISSUE TITLE
repex fail to start

### ISSUE THREAD

**Issue by haoyuanchen** [radical-cybertools/radical.repex.at#37]
**Error message in local computer:**

2015:08:24 11:39:12 6639   Thread-1     radical.repex.pk-patternB-multiD: [INFO    ] ComputePilot 'pilot.0000' state changed to Launching.
2015:08:24 11:39:34 6639   Thread-1     radical.repex.pk-patternB-multiD: [INFO    ] ComputePilot 'pilot.0000' state changed to PendingActive.
2015:08:24 11:49:17 6639   Thread-1     radical.repex.pk-patternB-multiD: [INFO    ] ComputePilot 'pilot.0000' state changed to Failed.
2015:08:24 11:49:17 6639   Thread-1     radical.repex.pk-patternB-multiD: [ERROR   ] Pilot error: [<radical.pilot.logentry.Logentry object at 0x7f7f10094650>, <radical.pilot.logentry.Logentry object at 0x7f7f10094890>, <radical.pilot.logentry.Logentry object at 0x7f7f100946d0>, <radical.pilot.logentry.Logentry object at 0x7f7f10094a90>, <radical.pilot.logentry.Logentry object at 0x7f7f10094b90>, <radical.pilot.logentry.Logentry object at 0x7f7f10094bd0>, <radical.pilot.logentry.Logentry object at 0x7f7f10094c10>, <radical.pilot.logentry.Logentry object at 0x7f7f10094c50>]
2015:08:24 11:49:17 6639   Thread-1     radical.repex.pk-patternB-multiD: [ERROR   ] RepEx execution FAILED.

**In Stampede, the agent.err file says:**

Lmod has detected the following error: The following module(s) are unknown:
"cluster"

   Please check the spelling or version number. Also try "module spider ..."

**RepEx version:** 0.2-feature-tuu-opt5-8518c14-
**Run:** 3d-tuu

**Comment by marksantcroos** [comment]
This is fixed in https://github.com/radical-cybertools/radical.pilot/issues/689 and will be part of the next release.

**Comment by haoyuanchen** [comment]
That's good. Thanks Mark!
