### ISSUE TITLE
TUU example with 1000 replicas fails on Gordon

### ISSUE THREAD

**Issue by antonst** [radical-cybertools/radical.repex.at#41]
with CU STDERR:

```
ssh_exchange_identification: Connection closed by remote host
```

**Comment by antonst** [comment]
strangely enough for smaller runs everything works fine. I would assume there are some nodes on gordon for which ssh keys are not properly configured.

**Comment by haoyuanchen** [comment]
Do you mean that the job isn't even starting with 1000 replicas, or it runs but failed halfway? If it failed halfway running, it could be that some replicas just didn't run for some reason. I saw this on Gordon too.

A quick check is to go to the job directory in the sandbox and do 

```
tail -n 1 unit*/*mdout
```

A normally terminated Amber job should say something like:

> |     wallclock() was called  290025 times

If something else, or not even a mdout file there, then that replica failed.

**Comment by marksantcroos** [comment]
Given that this is also a SDSC site, it might be the same SSH rate limiting as we see on Comet.

**Comment by antonst** [comment]
> Do you mean that the job isn't even starting with 1000 replicas, or it runs but failed halfway?

No job starts and some of the CU's finish the first Amber run, while others don't even start.

**Comment by antonst** [comment]
> Given that this is also a SDSC site, it might be the same SSH rate limiting as we see on Comet.

I would like to understand if this is specific to my account on Gordon. Mark, do you have the data for experiments with tasks other than bin/sleep or bin/date on Gordon which utilize more than 1000 cores concurrently?

**Comment by marksantcroos** [comment]
Its a per-node cu limit, not a total concurrent cu limit afaik.

**Comment by marksantcroos** [comment]
But I dont have such/any data on Gordon.

**Comment by antonst** [comment]
> Its a per-node cu limit, not a total concurrent cu limit afaik.

So in theory if we use more cores per CU we can avoid this issue?

**Comment by marksantcroos** [comment]
> So in theory if we use more cores per CU we can avoid this issue?

Yes, at least on Comet I empirically verified that.

**Comment by antonst** [comment]
Great! Will give it a try.
