### ISSUE TITLE
python setup.py install -> pip install

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.repex.at#45]
We know  for sure that RP does not always correctly install when _not_ installed via pip, and the group agreed (at some point) only to support pip as install method (as broken as it is).  Can the repex  documentation please changed to use pip?

**Comment by antonst** [comment]
> Can the repex documentation please changed to use pip?

Will do, but not before monday

**Comment by antonst** [comment]
repex can now be installed using:

```
pip install radical.repex
```
