### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by shantenujha** [radical-cybertools/radical.repex.at#47]
https://gist.github.com/shantenujha/1a87d2a0be248c2632c6

**Comment by antonst** [comment]
Can you please do:

```
export SDKROOT=
pip install radical.repex
```

**Comment by antonst** [comment]
did it work?

**Comment by shantenujha** [comment]
trying now.

**Comment by shantenujha** [comment]
no

**Comment by shantenujha** [comment]
https://gist.github.com/shantenujha/73c514ba7a992044cfe1

**Comment by shantenujha** [comment]
Should the value of SDKROOT value really be set to null ?

**Comment by antonst** [comment]
Please try this:

http://mpi4py.readthedocs.org/en/latest/appendix.html#mac-os-x-and-universal-sdk-python-builds

**Comment by antonst** [comment]
If you can install mpi4py on your laptop, e.g.:

```
pip install mpi4py
```

you should be OK. If this happens to be troublesome, in principle for this tutorial MPI support is not strictly required.

**Comment by shantenujha** [comment]
Hmm. I can try to fix this, but I fear that most students will not. Should I try on workflows.iu.xsede.org which is where most students will start?

**Comment by antonst** [comment]
> Should I try on workflows.iu.xsede.org which is where most students will start?

please do. Again, if it is difficult to install mpi4py on mac then I can remove that dependency.

**Comment by shantenujha** [comment]
Alas, mpi4py failed both on workflows.iu.xsede.org and my laptop.

I am not sure I understood, what you wanted me to do from: http://mpi4py.readthedocs.org/en/latest/appendix.html#mac-os-x-and-universal-sdk-python-builds

**Comment by shantenujha** [comment]
output of failed
pip install mpi4py 

at

https://gist.github.com/shantenujha/c6b736dec9f6cfaf4f87

**Comment by shantenujha** [comment]
BTW, wil you make the documentation page at:
   http://repex.readthedocs.org/en/devel-antons/pages/installation.html
consistent/similar to
  https://docs.google.com/spreadsheets/d/1sVMLiSoSbgE9vjLaQPxkEXDuoEjirudrT7JjKh6uI24/edit#gid=802012857

**Comment by shantenujha** [comment]
worth mentioning that the instructions given at:
http://repex.readthedocs.org/en/devel-antons/pages/installation.html

worked nicely.

i was able to install repex

(repex-env)[jha@workflow radical.repex]$ repex-version
0.2.1

**Comment by shantenujha** [comment]
.. on both workflow.iu.xsede.org and on my laptop (RandomDisorder)!!

**Comment by antonst** [comment]
Andre just mentioned that setup.py does not work with RP :-)

**Comment by shantenujha** [comment]
what does he know about RP? :)

**Comment by shantenujha** [comment]
i wasn't able to get further though (ie got stuck with repex-amber at:
  http://repex.readthedocs.org/en/devel-antons/pages/gettingstarted.html )

(repex-env)RandomDisorder:radical.repex shantenu$ repex-amber --input='tsu_remd_ace_ala_nme.json' --rconfig='stampede.json'
Traceback (most recent call last):
  File "/Users/shantenu/repex-env/bin/repex-amber", line 5, in <module>
    pkg_resources.run_script('radical.repex==0.2.1', 'repex-amber')
  File "/Users/shantenu/repex-env/lib/python2.7/site-packages/pkg_resources.py", line 488, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/shantenu/repex-env/lib/python2.7/site-packages/pkg_resources.py", line 1338, in run_script
    execfile(script_filename, namespace, namespace)
  File "/Users/shantenu/repex-env/lib/python2.7/site-packages/radical.repex-0.2.1-py2.7.egg/EGG-INFO/scripts/repex-amber", line 13, in <module>
    from amber_kernels_tex.kernel_pattern_s_tex       import KernelPatternStex
  File "/Users/shantenu/repex-env/lib/python2.7/site-packages/radical.repex-0.2.1-py2.7.egg/amber_kernels_tex/kernel_pattern_s_tex.py", line 23, in <module>
    import amber_kernels_tex.global_ex_calculator_mpi
ImportError: No module named global_ex_calculator_mpi

But i'll pause for now and resume after a few hours of sleep.

**Comment by antonst** [comment]
I know...

**Comment by antonst** [comment]
Can you please try now, with pip

**Comment by antonst** [comment]
should work now with: 0.2.2 repex version
