### ISSUE TITLE
provide relevant amber binaries on workflows.iu.xsede.org

### ISSUE THREAD

**Issue by shantenujha** [radical-cybertools/radical.repex.at#48]
For example on:

http://repex.readthedocs.org/en/devel-antons/pages/singledimexamples.html

and

http://repex.readthedocs.org/en/devel-antons/pages/gettingstarted.html#remd-input-file-for-amber-kernel

**Comment by antonst** [comment]
Amber was installed on workflow machine. Closing this now.

**Comment by marksantcroos** [comment]
Where? :)

**Comment by antonst** [comment]
closing as not relevant
