### ISSUE TITLE
Misleading claim

### ISSUE THREAD

**Issue by shantenujha** [radical-cybertools/radical.repex.at#49]
At: http://repex.readthedocs.org/en/devel-antons/pages/gettingstarted.html#remd-input-file-for-amber-kernel

we say:

We will also introduce two concepts, central to RepEx - Replica Exchange Patterns and Execution Strategies.

We do not. 

I would have deleted it, but this probably needs a proper reference to a proper (sub-)section

**Comment by antonst** [comment]
Fixed.
