### ISSUE TITLE
default NAMD crashes, have to use my own NAMD

### ISSUE THREAD

**Issue by haoyuanchen** [radical-cybertools/radical.repex.at#5]
Hi Antons,

When I try to run the example using the NAMD_2.9_Linux-x86 which is included in the package, the job crashes. I checked STDERR file and it says segmentation fault... I then switched to use my own NAMD (installed ~2 yrs ago, version is 2.8 instead of 2.9) and everything works fine. Not really a big issue but might still need to be fixed in the future. My OS is Fedora17 by the way.

Thanks!
Haoyuan

**Comment by antonst** [comment]
Hi Haoyuan,

Can you please specify which version of NAMD is actually installed on your system? To me it seems that NAMD_2.9_Linux-x86 is simply incompatible with the version of OS you are running on your system.

Thanks,
Antons

**Comment by haoyuanchen** [comment]
Yes, it could be the case that the 2.9 version just won't work on Fedora17. My version is NAMD 2.8 Linux-x86_64. I'll just keep using my version for now but I definitely need to update my Fedora some time...

Thanks!

**Comment by antonst** [comment]
OK, this has nothing to do with OS you are running. Shipped NAMD version is for 32-bit architecture, but yours is 64-bit (according to your current NAMD installation). But it would be useful to include 64-bit NAMD version in code base, so thanks for pointing this out!

**Comment by haoyuanchen** [comment]
That makes sense. Thank you!
