### ISSUE TITLE
flexible execution modes -- needs improvement in documentation

### ISSUE THREAD

**Issue by shantenujha** [radical-cybertools/radical.repex.at#52]
http://repex.readthedocs.org/en/devel-antons/pages/flexibleexecutionmodes.html

**Comment by antonst** [comment]
Is the the same as [#53](https://github.com/radical-cybertools/radical.repex/issues/53)? If yes, can I close it then?

**Comment by shantenujha** [comment]
Yes, I think this is the same. Apologies.
