### ISSUE TITLE
repex vs RepEx vs Repex

### ISSUE THREAD

**Issue by shantenujha** [radical-cybertools/radical.repex.at#55]
Need consistency in the usage of RepEx vs repex vs Repex

I find RepEx most commonly used, but find repex used (e.g., http://repex.readthedocs.org/en/devel-antons/index.html)

Welcome to repex’s documentation!

**Comment by haoyuanchen** [comment]
Just FYI, John Chodera's group has a repo called repex and it's also about replica exchange...so we can either use RepEx or Repex but not repex

**Comment by antonst** [comment]
> Welcome to repex’s documentation!

Fixed now.

Shantenu can you please point me to where you have found Repex in documentation?

**Comment by shantenujha** [comment]
I don't remember offhand, but when I go back to review, I will look for Repex and point out.

**Comment by antonst** [comment]
> Just FYI, John Chodera's group has a repo called repex and it's also about replica exchange

Can you point me to that repo please?

**Comment by haoyuanchen** [comment]
> Can you point me to that repo please?

https://github.com/choderalab/repex

**Comment by antonst** [comment]
Is this issue still relevant?

**Comment by antonst** [comment]
Closing due to lack of response.
