### ISSUE TITLE
Testing matrix line 16: Couldn't find file containing "exchange_mpi"

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.repex.at#61]
I wasn't able to find out which file I need to edit to set "exchange_mpi" to False.

```
repex.examples/examples/amber$ grep -rl "exchange_mpi" *
repex.examples/examples/amber$
```

**Comment by antonst** [comment]
It has been decided to disable option to run exchange with mpi due to mpi4py installation issues so documentation currently does not specify how to do this. by default this parameter is set to False

**Comment by antonst** [comment]
This happened after I created a testing document, sorry about that.
