### ISSUE TITLE
  Testing matrix line 14: No method to specify queue

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.repex.at#62]
I am not sure if its required for the workshop (since we will have a separate allocation with possibly minimal queue time), but in archer.json there is no key-value entry to specify the queue.

**Comment by antonst** [comment]
true, entry is not there but documentation explicitly specifies how to set this:
http://repex.readthedocs.org/en/master/pages/gettingstarted.html#resource-configuration-file

**Comment by vivek-bala** [comment]
Thanks Antons.
