### ISSUE TITLE
No verbose msgs/logs

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.repex.at#63]
When running `repex-amber --input='t_remd_ala10.json' --rconfig='<resource>.json'` towards archer. I don't see any msgs printed. But I checked on archer, the job seems to have been submitted. Should I be setting any verbosity variable (similar to RADICAL_PILOT_VERBOSE) ?

**Comment by antonst** [comment]
line 6 of testing document asks you to set:

```
export RADICAL_REPEX_VERBOSE=info
```

**Comment by vivek-bala** [comment]
ah missed that. sry.
