### ISSUE TITLE
problem with generalized branch

### ISSUE THREAD

**Issue by haoyuanchen** [radical-cybertools/radical.repex.at#76]
I tried to run a 2D UU simulation with the feature/perfopt_gen branch, but I got this error:

2016-03-25 17:43:54,291: radical.saga.pty    : MainProcess                     : MainThread     : ERROR   : DoesNotExist: file copy failed: mput  "/home/haoyuan/radical.repex/examples/amber/tuu_remd_inputs/ace_ala_nme_coors_8x8/salt_conc_pre_exec.py" "/work/02938/chen1990/radical.pilot.sandbox/rp.session.prot-55-247.rutgers.edu.haoyuan.016885.0000-pilot.0000/staging_area/ace_ala_nme.inpcrd.0.0"

It's trying to copy a script for salt concentration exchange, which is not needed here. Also, it seems that it's trying to copy that file to a coordinate file...

**Comment by antonst** [comment]
Can you please provide your simulation input file?

**Comment by haoyuanchen** [comment]
{
    "remd.input": {
        "re_pattern": "S",
        "number_of_cycles": "4",
        "input_folder": "tuu_remd_inputs",
        "input_file_basename": "ace_ala_nme_remd",
        "amber_input": "ace_ala_nme.mdin",
        "us_template": "ace_ala_nme_us.RST",
        "amber_parameters": "ace_ala_nme.parm7",
        "amber_coordinates_folder": "ace_ala_nme_coors_8x8",
        "same_coordinates": "False",
        "group_exec": "False",
        "init_temp": "300.0",
        "replica_mpi": "True",
        "replica_cores": "2",
        "steps_per_cycle": "5000",
        "download_mdinfo": "False",
        "download_mdout" : "False"
        },
    "dim.input": {
        "d1": {
            "type" : "umbrella",
            "number_of_replicas": "4",
            "min_us_param": "45.0",
            "max_us_param": "360.0"
            },
        "d2": {
            "type" : "umbrella",
            "number_of_replicas": "4",
            "min_us_param": "45.0",
            "max_us_param": "360.0"
            }
    }
}

**Comment by antonst** [comment]
Thanks, can you please try to re-run now?

**Comment by haoyuanchen** [comment]
It ran for several cycles and then crashed. However, I looked at each replica, none of them actually finished their MD cycles--Amber wasn't even executed in the MD cycle. But it still went through several cycles and no exchange occurred.

**Comment by antonst** [comment]
This is fixed now in `feature/perfopt_gen` branch. Also I recommend to set `number of cores = node size`.
