### ISSUE TITLE
TSU problem in perfopt_gen branch

### ISSUE THREAD

**Issue by haoyuanchen** [radical-cybertools/radical.repex.at#78]
The simulation cannot run because in the mdin files, the @salt@ placeholder were not replaced by corresponding values.

**Comment by antonst** [comment]
Can you please paste you input file here?

**Comment by haoyuanchen** [comment]
JSON file:

{
    "remd.input": {
        "re_pattern": "S",
        "number_of_cycles": "3",
        "input_folder": "tsu_remd_inputs",
        "input_file_basename": "dna_remd",
        "amber_input": "dna.mdin",
        "us_template": "dna_us.RST",
        "amber_parameters": "dna.parm7",
        "amber_coordinates_folder": "dna_coors",
        "same_coordinates": "False",
        "group_exec": "False",
        "init_temp": "288.0",
        "replica_mpi": "False",
        "replica_cores": "1",
        "steps_per_cycle": "1000",
        "download_mdinfo": "False",
        "download_mdout" : "False"
        },
    "dim.input": {
         "d2": {
            "type" : "salt",
            "number_of_replicas": "4",
            "exchange_replica_cores" : "4",
            "min_salt": "0.0",
            "max_salt": "0.15"
            },
        "d1": {
            "type" : "temperature",
            "number_of_replicas": "2",
            "min_temperature": "288.0",
            "max_temperature": "289.0"
            },
        "d3": {
            "type" : "umbrella",
            "number_of_replicas": "12",
            "min_us_param": "67.5",
            "max_us_param": "97.5"
            }
    }
}

Template mdin file:

NVT equilibration
 &cntrl
  imin = 0,
  ntx = @ntx@,
  irest = @irest@,
  ntpr = @nstlim@,
  ntwr = @nstlim@,
  ntwx = @nstlim@,
  ntf = 2, 
  ntc = 2,
  ntb = 0,
  igb = 1,
  cut = 999.0,
  nstlim = @nstlim@,
  dt = 0.002,
  extdiel = 81.946,
  saltcon = @salt@,
  temp0 = @temp@,
  ntt = 3,
  gamma_ln = 5.0,
  ig = -1,
  nmropt = 1
 /
 &wt
  type = 'DUMPFREQ', istep1 = 10,
 /
 &wt
   type = 'END'
 /
DISANG = @disang@
DUMPAVE = @disang@.out

**Comment by antonst** [comment]
There is no `dna_remd` in examples directory, so I can't test your input file,  but I have pushed a fix which should solve this problem. Can you please try to re-run your simulation?

**Comment by antonst** [comment]
Sorry, I have found input folder. It seems to work fine, I just had to rename coordinate files, so that they don't have a .0 at the end.

**Comment by antonst** [comment]
Can you please verify this?

**Comment by haoyuanchen** [comment]
Now the simulation could run. I'm seeing exchanges in both T and S dimensions, but not U dimension. That might be related to the exchange issue we've been discussing, but we can close this ticket now.

Thanks!
