### ISSUE TITLE
The scheme #2 and #2a seem not working for AMBER on Stampede 

### ISSUE THREAD

**Issue by taisung** [radical-cybertools/radical.repex.at#8]
I tried the amber example with Scheme #2 and #2a on Stampede and the exchange part was not executed with the following error:

  File "launch_simulation_scheme_2_amber.py", line 55, in <module>
    pilot_kernel.run_simulation( replicas, pilot_object, session, md_kernel )
  File "/usr/people/taisung/Data/CDI-SAGA/RepEx/src/radical/repex/pilot_kernels/pilot_kernel_scheme_2.py", line 119, in run_simulation
    swap_matrix = self.compose_swap_matrix(replicas)
  File "/usr/people/taisung/Data/CDI-SAGA/RepEx/src/radical/repex/pilot_kernels/pilot_kernel_scheme_2.py", line 67, in compose_swap_matrix
    f = open(column_file)
IOError: [Errno 2] No such file or directory: 'matrix_column_0_0.dat'

**Comment by antonst** [comment]
Hi Taisung, to me this appears as first simulation cycle never being finished and in the result of that no data has been transferred back. Is this correct? Do you see Amber output files in your working directory? Can you please post your input file here as well?

Thanks,
Antons

**Comment by taisung** [comment]
Hi Antons,

```
           In fact, I just used your examples.  Both amber and namd finished the first simulation but no exchange happened.
```

Taisung
