### ISSUE TITLE
Parameter in other dimensions recognized as temperature in exchanges

### ISSUE THREAD

**Issue by haoyuanchen** [radical-cybertools/radical.repex.at#80]
In the radical_pilot_cu_launch_script.sh files which are located in the individual CU folders, there's an "init_temp" variable which is used as temperature for exchange calculations. However, in TUU cases it read in one of the umbrella parameters from input json file as the temperature, and in TSU cases it read in one of the salt parameters. This caused incorrect energies for exchange calculations and incorrect exchange rates.

Also, in temperature exchanges, the ensemble temperature (from initial input) should be used for exchange calculations instead of instantaneous temperatures (from history files).

**Comment by antonst** [comment]
I have addressed both issues in devel now. Can you please rerun the experiments and check energy calculations again?

**Comment by antonst** [comment]
At least for TUU experiment with your input files I now see lots of exchanges in U dimension.

**Comment by haoyuanchen** [comment]
> At least for TUU experiment with your input files I now see lots of exchanges in U dimension.

Yes, I'm seeing lots of exchanges too. I still have to run different tests to check the exchange rate and also look into the matrix column file for details, but I think we can close this issue for now. Thanks!

**Comment by antonst** [comment]
Can you please summarize tests for energy calculations you performed yesterday, at least in a textual form? we are currently working on a testing suite for repex and it would be very useful to add those tests, so that we don't have check for this bug manually.

**Comment by haoyuanchen** [comment]
> Can you please summarize tests for energy calculations you performed yesterday, at least in a textual form? we are currently working on a testing suite for repex and it would be very useful to add those tests, so that we don't have check for this bug manually.

Sure. I'll try to do that.
Also, I've found some new problems in the exchange and I'll open a new ticket for that soon.

**Comment by antonst** [comment]
OK, great :-)
