### ISSUE TITLE
Sander executable incorrectly pathed for SuperMIC

### ISSUE THREAD

**Issue by SrinivasMushnoori** [radical-cybertools/radical.repex.at#87]
Hi folks

While running scaling experiments on SuperMIC I noticed that none of the replicas would actually run after the CU's had been instantiated. It gave me the following error: 

_/bin/bash: /home/antontre/amber14/bin/sander: Permission denied
Killed by signal 15._

I narrowed the issue down to _radical.repex/src/radical/repex/kernels/kernels.py_ where upon investigating, sure enough, the Sander executable was sourced as:

_"executable" : "/home/antontre/amber14/bin/sander"_

Changing that to the correct location of sander on SuperMIC as:

 _"executable" : "/usr/local/packages/amber/14/INTEL-140-MVAPICH2-2.0/bin/sander"_

and reinstalling seems to have fixed the issue. Simulations are running for now and scaling experiments are proceeding as planned. Please let me know if you have further comments or if you feel that I may have overlooked something.

**Comment by ibethune** [comment]
I think one of you should just make the change then, since you seem to have reported and solved the problem already!

**Comment by antonst** [comment]
addressed in devel
