### ISSUE TITLE
testing document

### ISSUE THREAD

**Issue by shantenujha** [radical-cybertools/radical.repex.at#9]
Just wandering why the tester has to go through the manual process of installing 
radical.utils, saga, radical-pilot before using/trying repex?

**Comment by antonst** [comment]
These were the latest installation instructions for RP I am aware of.

Thanks,
Antons

**Comment by andre-merzky** [comment]
saga and utils have been released meanwhile -- no need to install those from git.

**Comment by oleweidner** [comment]
I think Antons still relies on features that are not release yet. Is that correct? If so, please update the installation instructions soon after the upcoming RP release. Thanks

**Comment by antonst** [comment]
This indeed appears to be the case Ole.

Thanks,
Antons
